openapi: 3.0.0
info:
  title: wallet web app demo
  version: '1.1'
servers:
  - url: 'http://localhost:3000'
paths:
  '/wallets/{walletName}':
    parameters:
      - schema:
          type: string
        name: walletName
        in: path
        required: true
    get:
      summary: get wallet info
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/wallet'
              examples: {}
      operationId: get-wallets-walletName
      description: get wallet object
  '/wallets/{walletName}/tokens':
    parameters:
      - schema:
          type: string
        name: walletName
        in: path
        required: true
    get:
      summary: get token list in wallet
      tags: []
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  tokens:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      required:
                        - id
                        - capture_id
                        - capture_photo_url
                        - created_at
                        - planter_id
                        - planter_name
                        - planter_photo_url
                      properties:
                        id:
                          type: string
                          minLength: 1
                        capture_id:
                          type: string
                          minLength: 1
                        capture_photo_url:
                          type: string
                          minLength: 1
                        created_at:
                          type: string
                          minLength: 1
                        planter_id:
                          type: string
                          minLength: 1
                        planter_name:
                          type: string
                          minLength: 1
                        planter_photo_url:
                          type: string
                          minLength: 1
                required:
                  - tokens
                x-examples:
                  example-1:
                    tokens:
                      - id: c488301f-1117-48c3-8866-3c38f28d3f25
                        capture_id: '932758'
                        capture_photo_url: 'https://treetracker-production-images.s3.eu-central-1.amazonaws.com/2021.05.19.09.42.48_-4.882362633999999_38.38042393_e930d565-e28c-4e28-a313-16c85df989f1_IMG_20210517_143630_167714448.jpg'
                        created_at: '5/17/2021, 7:36:18 PM'
                        planter_id: '123'
                        planter_name: Issa H
                        planter_photo_url: 'https://treetracker-production-images.s3.eu-central-1.amazonaws.com/2021.05.11.18.37.00_-4.91963284_38.52757506_adc35f9c-b76e-4798-b587-70f5fba06b89_IMG_20210511_101502_-1595081185.jpg'
                      - id: 951554de-145c-11ec-82a8-0242ac130003
                        capture_id: '933042'
                        capture_photo_url: 'https://treetracker-production-images.s3.eu-central-1.amazonaws.com/2021.05.19.09.49.19_-4.881696978000001_38.37997515399998_47fc629b-27e9-4b58-b31a-3a35e5bbc3f0_IMG_20210518_121452_1024002290.jpg'
                        created_at: '5/18/2021, 5:14:48 PM'
                        planter_id: '123'
                        planter_name: Issa H
                        planter_photo_url: 'https://treetracker-production-images.s3.eu-central-1.amazonaws.com/2021.05.11.18.37.00_-4.91963284_38.52757506_adc35f9c-b76e-4798-b587-70f5fba06b89_IMG_20210511_101502_-1595081185.jpg'
              examples:
                example-1:
                  value:
                    tokens:
                      - id: c488301f-1117-48c3-8866-3c38f28d3f25
                        capture_id: '932758'
                        capture_photo_url: 'https://treetracker-production-images.s3.eu-central-1.amazonaws.com/2021.05.19.09.42.48_-4.882362633999999_38.38042393_e930d565-e28c-4e28-a313-16c85df989f1_IMG_20210517_143630_167714448.jpg'
                        created_at: '5/17/2021, 7:36:18 PM'
                        planter_id: '123'
                        planter_name: Issa H
                        planter_photo_url: 'https://treetracker-production-images.s3.eu-central-1.amazonaws.com/2021.05.11.18.37.00_-4.91963284_38.52757506_adc35f9c-b76e-4798-b587-70f5fba06b89_IMG_20210511_101502_-1595081185.jpg'
                      - id: 951554de-145c-11ec-82a8-0242ac130003
                        capture_id: '933042'
                        capture_photo_url: 'https://treetracker-production-images.s3.eu-central-1.amazonaws.com/2021.05.19.09.49.19_-4.881696978000001_38.37997515399998_47fc629b-27e9-4b58-b31a-3a35e5bbc3f0_IMG_20210518_121452_1024002290.jpg'
                        created_at: '5/18/2021, 5:14:48 PM'
                        planter_id: '123'
                        planter_name: Issa H
                        planter_photo_url: 'https://treetracker-production-images.s3.eu-central-1.amazonaws.com/2021.05.11.18.37.00_-4.91963284_38.52757506_adc35f9c-b76e-4798-b587-70f5fba06b89_IMG_20210511_101502_-1595081185.jpg'
      operationId: get-wallets-walletName-tokens
  '/trees/{treeId}':
    parameters:
      - schema:
          type: string
        name: treeId
        in: path
        required: true
    get:
      summary: get tree info
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tree'
      operationId: get-trees-treeId
  '/planters/{planterId}':
    parameters:
      - schema:
          type: string
        name: planterId
        in: path
        required: true
    get:
      summary: get planter info
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/planter'
              examples: {}
      operationId: get-planters-planterId
  '/impact-managers/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: get impact manager info
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/impact-manager'
      operationId: get-impact-managers-id
  '/impact-producers/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: get impact producer info
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/impact-producer'
      operationId: get-impact-producers-id
  '/tokens/{tokenId}':
    parameters:
      - schema:
          type: string
        name: tokenId
        in: path
        required: true
    get:
      summary: get token info
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/token'
      operationId: get-tokens-tokenId
  '/tokens/{tokenId}/transactions':
    parameters:
      - schema:
          type: string
        name: tokenId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  transactions:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      required:
                        - id
                        - sender_wallet_id
                        - sender_wallet_name
                        - receiver_wallet_id
                        - receiver_wallet_name
                        - created_at
                      properties:
                        id:
                          type: string
                          minLength: 1
                        sender_wallet_id:
                          type: string
                          minLength: 1
                        sender_wallet_name:
                          type: string
                          minLength: 1
                        receiver_wallet_id:
                          type: string
                          minLength: 1
                        receiver_wallet_name:
                          type: string
                          minLength: 1
                        created_at:
                          type: string
                          minLength: 1
                required:
                  - transactions
                x-examples:
                  example-1:
                    transactions:
                      - id: 43ad1a4e-1468-11ec-82a8-0242ac130003
                        sender_wallet_id: 4f4a4426-1468-11ec-82a8-0242ac130003
                        sender_wallet_name: Zaven
                        receiver_wallet_id: 5e1e4ab0-1468-11ec-82a8-0242ac130003
                        receiver_wallet_name: Stephanie
                        created_at: '5/17/2021, 7:36:18 PM'
                      - id: 8c9ae04c-1468-11ec-82a8-0242ac130003
                        sender_wallet_id: 5e1e4ab0-1468-11ec-82a8-0242ac130003
                        sender_wallet_name: Stephanie
                        receiver_wallet_id: b4f97ada-1468-11ec-82a8-0242ac130003
                        receiver_wallet_name: Meize
                        created_at: '5/19/2021, 9:21:11 PM'
              examples:
                example-transaction:
                  value:
                    transactions:
                      - id: 43ad1a4e-1468-11ec-82a8-0242ac130003
                        sender_wallet_id: 4f4a4426-1468-11ec-82a8-0242ac130003
                        sender_wallet_name: Zaven
                        receiver_wallet_id: 5e1e4ab0-1468-11ec-82a8-0242ac130003
                        receiver_wallet_name: Stephanie
                        created_at: '5/17/2021, 7:36:18 PM'
                      - id: 8c9ae04c-1468-11ec-82a8-0242ac130003
                        sender_wallet_id: 5e1e4ab0-1468-11ec-82a8-0242ac130003
                        sender_wallet_name: Stephanie
                        receiver_wallet_id: b4f97ada-1468-11ec-82a8-0242ac130003
                        receiver_wallet_name: Meize
                        created_at: '5/19/2021, 9:21:11 PM'
      operationId: get-tokens-tokenId-transactions
components:
  schemas:
    wallet:
      title: wallet
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        token_in_wallet:
          type: number
        photo_url:
          type: string
      x-examples:
        example-1:
          value:
            id: 4d96c4ca-1444-11ec-82a8-0242ac130003
            name: SustainablyRun
            token_in_wallet: 2
            photo_url: 'https://dadior.s3.ap-northeast-1.amazonaws.com/wallet-avatar.jpeg'
    token:
      description: ''
      type: object
      properties:
        id:
          type: string
          minLength: 1
        capture_id:
          type: string
          minLength: 1
        capture_photo_url:
          type: string
          minLength: 1
        created_at:
          type: string
          minLength: 1
        planter_id:
          type: string
          minLength: 1
        planter_name:
          type: string
          minLength: 1
        planter_photo_url:
          type: string
          minLength: 1
      required:
        - id
        - capture_id
        - capture_photo_url
        - created_at
        - planter_id
        - planter_name
        - planter_photo_url
      x-examples: {}
    tree:
      description: ''
      type: object
      properties:
        id:
          type: number
        photo_url:
          type: string
          minLength: 1
        verified:
          type: boolean
        token_id:
          type: string
          minLength: 1
        impact_manager_id:
          type: string
          minLength: 1
        impact_producer_id:
          type: string
          minLength: 1
        created_at:
          type: string
          minLength: 1
        lat:
          type: number
        lon:
          type: number
        species:
          type: string
          minLength: 1
        planter_id:
          type: number
      required:
        - id
        - photo_url
        - verified
        - token_id
        - impact_manager_id
        - impact_producer_id
        - created_at
        - lat
        - lon
        - species
        - planter_id
      x-examples:
        treeexample:
          id: 933042
          photo_url: 'https://treetracker-production-images.s3.eu-central-1.amazonaws.com/2021.05.19.09.49.19_-4.881696978000001_38.37997515399998_47fc629b-27e9-4b58-b31a-3a35e5bbc3f0_IMG_20210518_121452_1024002290.jpg'
          verified: true
          token_id: d4bb294b-8c75-4e0f-af43-1cd9a35e1033
          impact_manager_id: 8599f832-145e-11ec-82a8-0242ac130003
          impact_producer_id: a0b6b70e-145e-11ec-82a8-0242ac130003
          created_at: '5/18/2021, 5:14:48 PM'
          lat: -4.881696978000001
          lon: 38.37997515399998
          species: Markhamia lutea
          planter_id: 5
          value:
            id: 933042
            photo_url: 'https://treetracker-production-images.s3.eu-central-1.amazonaws.com/2021.05.19.09.49.19_-4.881696978000001_38.37997515399998_47fc629b-27e9-4b58-b31a-3a35e5bbc3f0_IMG_20210518_121452_1024002290.jpg'
            verified: true
            token_id: d4bb294b-8c75-4e0f-af43-1cd9a35e1033
            impact_manager_id: 8599f832-145e-11ec-82a8-0242ac130003
            impact_producer_id: a0b6b70e-145e-11ec-82a8-0242ac130003
            created_at: '5/18/2021, 5:14:48 PM'
            lat: -4.881696978000001
            lon: 38.37997515399998
            species: Markhamia lutea
            planter_id: 5
    planter:
      description: ''
      type: object
      properties:
        id:
          type: number
        photo_url:
          type: string
          minLength: 1
        name:
          type: string
          minLength: 1
      required:
        - id
        - photo_url
        - name
      x-examples:
        example-planter:
          id: 5
          photo_url: 'https://treetracker-production-images.s3.eu-central-1.amazonaws.com/2021.05.11.18.37.00_-4.91963284_38.52757506_adc35f9c-b76e-4798-b587-70f5fba06b89_IMG_20210511_101502_-1595081185.jpg'
          name: Issa H
          value:
            id: 5
            photo_url: 'https://treetracker-production-images.s3.eu-central-1.amazonaws.com/2021.05.11.18.37.00_-4.91963284_38.52757506_adc35f9c-b76e-4798-b587-70f5fba06b89_IMG_20210511_101502_-1595081185.jpg'
            name: Issa H
    impact-manager:
      description: ''
      type: object
      properties:
        id:
          type: string
          minLength: 1
        photo-url:
          type: string
          minLength: 1
        name:
          type: string
          minLength: 1
      required:
        - id
        - photo-url
        - name
      x-examples:
        example-finorx:
          id: ab0451aa-1461-11ec-82a8-0242ac130003
          photo-url: 'https://dadior.s3.ap-northeast-1.amazonaws.com/3_web_monarch_83f37fd1-c233-46b5-9eed-2b57e4040a96_200x+1.png'
          name: FinorX
          value:
            id: ab0451aa-1461-11ec-82a8-0242ac130003
            photo-url: 'https://dadior.s3.ap-northeast-1.amazonaws.com/3_web_monarch_83f37fd1-c233-46b5-9eed-2b57e4040a96_200x+1.png'
            name: FinorX
    impact-producer:
      description: ''
      type: object
      properties:
        id:
          type: string
          minLength: 1
        photo_url:
          type: string
          minLength: 1
        name:
          type: string
          minLength: 1
      required:
        - id
        - photo_url
        - name
      x-examples:
        example-fcc:
          id: 3e530aaa-1462-11ec-82a8-0242ac130003
          photo_url: 'https://dadior.s3.ap-northeast-1.amazonaws.com/image+8.png'
          name: FCC
          value:
            id: 3e530aaa-1462-11ec-82a8-0242ac130003
            photo_url: 'https://dadior.s3.ap-northeast-1.amazonaws.com/image+8.png'
            name: FCC
